# Generated by Django 4.0.4 on 2022-07-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('test', models.TextField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zikr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zikr', models.CharField(blank=True, max_length=3000, null=True)),
            ],
        ),
    ]
