# Generated by Django 4.0.4 on 2022-07-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_user_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='zikr',
            name='zikr_arabic',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='zikr',
            name='zikr_mean',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
